### PR TITLE
add Flix and Associated Effects

### PR DESCRIPTION
**Pull request by mlutze**
This PR adds the Flix programming language to the software list and a recent paper to the papers list.

### CODE REVIEW

**Review by dhil — APPROVED** [review]
LGTM. Thanks!

**Comment by dhil** [comment]
> The failures in the CI appear to be unrelated to this addition.

Yes agreed. We can do either of two things:

1. Update [lychee ignore set](https://github.com/yallop/effects-bibliography/blob/master/.lycheeignore) to include these failures;
2. or wait for @yallop to merge this PR. I can only merge things that tick all green on the CI.

**Comment by yallop** [comment]
I'll take a closer look soon, but some of the errors appear to be transient, so I've re-run the job.

**Comment by dhil** [comment]
> [..] but some of the errors appear to be transient, so I've re-run the job.

Yes. I re-run them (yesterday?) already. It appears the location of @lucques' thesis has changed from http://lukas.convnet.de/proj/master/thesis.pdf to http://lukas.convnet.de/proj/master/res/thesis.pdf so that should be updated. The other failures appears to be due to expired SSL certificates. I am able to "click through" the warnings in my browser to access the respective pdfs.

**Comment by yallop** [comment]
Thank you for the contribution, @mlutze!

**Pull request merged**
