### PR TITLE
Add "Algebraic Effects for Functional Programming"

### PR DESCRIPTION
**Pull request by omentic**

### CODE REVIEW

**Comment by dhil** [comment]
I think this is the techreport version of "Type directed compilation of row-typed algebraic effects" POPL'17 -- if I am correct, then we should add it to this entry.

**Comment by omentic** [comment]
Ah, it looks like it's a separate technical report, but nearly identical in content? Strange.

I've added in a link to both technical reports as v1 and v2 (though I'm not sure which is which) and put the alternate title underneath the existing paper. LMK if I should change / remove anything!

**Comment by dhil** [comment]
I think this technical report is simply an early version of the POPL paper, and that Daan was using a different title then. I think we should just stick with one title, which should be the title of the POPL paper.

**Comment by omentic** [comment]
OK! I think I'll just close this then since there's already links to that paper :+1:

**Pull request closed without merging**
